### PR TITLE
Chatbot Integration

### PR DESCRIPTION
**Pull request by MasbiMpho**
- Adding Chatbot User Interface 
- Adding Chatbot Functionality
- Adding Animation to certain Chabot Functionality

### CODE REVIEW

**Review by HitekoMabasa — COMMENTED** [review]
Does your chatbot keep previous data when you close it or each time you close it refreshes and starts a new conversation?

**Comment by MasbiMpho** [comment]
> Does your chatbot keep previous data when you close it or each time you close it refreshes and starts a new conversation?

Both. If you click close (X) it clears the conversations but if you click minimize(-) it closes the chat without deleting the conversation

**Review by thaboxan — COMMENTED** [review]
Looks good

**Review by Miixo22 — APPROVED** [review]
I like the ui

**Review by HitekoMabasa — APPROVED** [review]
Great, I don't think there is anything missing .

**Pull request merged**
